dist: xenial

language: go

go:
  - 1.13.x

git:
  depth: 1

install: true

notifications:
  email: false


env:
  global:
    - DBUSER=xiovv
    - DBSTR=mernstackcourse
    - DBPASS=gurabijas112


before_script:
  - go get -d ./...

script:
  - go test -v ./...